export const PLAYER_ALIASES: Record<string, string> = {
    // Goalkeepers
    'vicario': 'guglielmo vicario',
    'dubravka': 'martin dubravka',
    'alisson': 'alisson becker',
    'ederson': 'ederson moraes',
    'onana': 'andre onana',
    'areola': 'alphonse areola',
    'neto': 'norberto murara neto',
    'donnarumma': 'gianluigi donnarumma',
    'ramsdale': 'aaron ramsdale',
    'lammens': 'senne lammens',
    'hermansen': 'mads hermansen',
    'perri': 'lucas perri',
    'roefs': 'robin roefs',
    'fabianski': 'lukasz fabianski',
    
    // Defenders
    'taa': 'trent alexander-arnold',
    'trent': 'trent alexander-arnold',
    'robertson': 'andrew robertson',
    'vvd': 'virgil van dijk',
    'virgil': 'virgil van dijk',
    'dias': 'ruben dias',
    'saliba': 'william saliba',
    'gabriel': 'gabriel magalhaes',
    'cancelo': 'joao cancelo',
    'hincapie': 'piero hincapie',
    'burn': 'dan burn',
    'schar': 'fabian schar',
    'justin': 'james justin',
    'guehi': 'marc guehi',
    'chilwell': 'ben chilwell',
    'porro': 'pedro porro',
    'ait nouri': 'rayan ait-nouri',
    'hato': 'jorrel hato',
    'leoni': 'giovanni leoni',
    'thiaw': 'malick thiaw',
    'lindelof': 'victor lindelof',
    'krejci': 'ladislav krejci',
    'mosquera': 'cristhian mosquera',
    'ugochukwu': 'lesley ugochukwu',
    'geertruida': 'lutsharel geertruida',
    'masuaku': 'arthur masuaku',
    
    // Midfielders
    'jota': 'diogo jota',
    'gakpo': 'cody gakpo',
    'mbeumo': 'bryan mbeumo',
    'bruno': 'bruno fernandes',
    'kdb': 'kevin de bruyne',
    'martinelli': 'gabriel martinelli',
    'wirtz': 'florian wirtz',
    'palmer': 'cole palmer',
    'paqueta': 'lucas paqueta',
    'rice': 'declan rice',
    'elanga': 'anthony elanga',
    'ndiaye': 'iliman ndiaye',
    'anderson': 'elliot anderson',
    'reijnders': 'tijjani reijnders',
    'arias': 'jhon arias',
    'simons': 'xavi simons',
    'bakwa': 'dilane bakwa',
    'ndoye': 'dan ndoye',
    'kalimuendo': 'arnaud kalimuendo',
    'palhinha': 'joao palhinha',
    'dibling': 'tyler dibling',
    'fernandes': 'mateus fernandes',
    'stach': 'anton stach',
    'magassa': 'soungoutou magassa',
    'rohl': 'merlin rohl',
    'luiz': 'douglas luiz',
    'xhaka': 'granit xhaka',
    
    // Forwards
    'haaland': 'erling haaland',
    'nunez': 'darwin nunez',
    'jesus': 'gabriel jesus',
    'cunha': 'matheus cunha',
    'wood': 'chris wood',
    'joao pedro': 'joao pedro',
    'johnson': 'brennan johnson',
    'watkins': 'ollie watkins',
    'isak': 'alexander isak',
    'toney': 'ivan toney',
    'solanke': 'dominic solanke',
    'ferguson': 'evan ferguson',
    'gyokeres': 'viktor gyokeres',
    'ekitike': 'hugo ekitike',
    'sesko': 'benjamin sesko',
    'woltemade': 'nick woltemade',
    'kolo muani': 'randal kolo muani',
    'brobbey': 'brian brobbey',
    'arokodare': 'tolu arokodare',
    'broja': 'armando broja',
    'calvert-lewin': 'dominic calvert-lewin',
    'wilson': 'callum wilson',
    'uche': 'christantus uche',
    'mateta': 'jean-philippe mateta',
    'larsen': 'jorgen strand larsen'
  };